eureka:
    client:
#        fetch-registry: false   #是否检索服务
#        register-with-eureka: false   #是否向服务注册中心注册自己
    instance:
        lease-expiration-duration-in-seconds: 90  #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance(默认为90秒)
        lease-renewal-interval-in-seconds: 30 #表示eureka client发送心跳给server端的频率
        prefer-ip-address: true
        health-check-url-path: /actuator/health
        status-page-url-path: /actuator/info
    server:
        enableSelfPreservation: true   #关闭自我保护机制 调试时使用
spring:
    application:
        name: cloud-discovery
    profiles:
        active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  path: d:/logs/${spring.application.name}